[project]
name = "vision-transformers-cifar10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "odach>=0.3.0",
    "timm>=1.0.22",
    "vit-pytorch>=1.15.7",
    "wandb>=0.23.0",
]
